version: '3'
services:

  mongodb:
    image: mongo
    ports:
    - 27017:27017

  tweet_collector:
    build: tweet_collector/
    volumes:
    - ./tweet_collector/:/app
    depends_on:
    - mongodb

  etl:
    container_name: etl_container
    build: etl_job/
    volumes:
    - ./etl_job/:/app
    depends_on: 
    - mongodb
    - postgresdb

  postgresdb:
    container_name: postgresdb_container
    image: postgres
    ports:
    - 5555:5432
    environment:
    - POSTGRES_HOST_AUTH_METHOD=trust
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=db_postgres
